Fix a compilation error when `qreal` is `float`
On i686 and x86_64, `qreal` is `double`. But on armv7, it is
`float`. That creates a compilation error:

    g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtXml -I/usr/include -I/usr/X11R6/include -I.moc -I. -o .obj/manipulatedCameraFrame.o manipulatedCameraFrame.cpp
    In file included from quaternion.h:26:0,
                     from keyFrameInterpolator.h:29,
                     from camera.h:26,
                     from camera.cpp:24:
    vec.h: In member function 'qglviewer::Vec::operator const double*() const':
    vec.h:175:10: error: cannot convert 'const qreal* {aka const float*}' to 'const double*' in return
       return v_;
              ^~

https://kojipkgs.fedoraproject.org//work/tasks/5657/14905657/build.log

The fix is to use `qreal` everywhere, instead of `double`.